#include "LFOSeqTrack.h"
#include "LFOTrackRef.h"
#include "MidiClock.h"
#include "MCLSeq.h"
#include <string.h>

// Generated by tools/generate_lfo_tables.py.
const uint8_t LFOSeqTrack::wav_tables[LFO_TABLE_COUNT][WAV_LENGTH] PROGMEM = {
  {
    128, 134, 140, 146, 152, 158, 165, 170, 176, 182, 188, 193, 198, 203, 208, 213,
    218, 222, 226, 230, 234, 237, 240, 243, 245, 248, 250, 251, 253, 254, 254, 255,
    255, 255, 254, 254, 253, 251, 250, 248, 245, 243, 240, 237, 234, 230, 226, 222,
    218, 213, 208, 203, 198, 193, 188, 182, 176, 170, 165, 158, 152, 146, 140, 134,
    128, 121, 115, 109, 103,  97,  90,  85,  79,  73,  67,  62,  57,  52,  47,  42,
     37,  33,  29,  25,  21,  18,  15,  12,  10,   7,   5,   4,   2,   1,   1,   0,
      0,   0,   1,   1,   2,   4,   5,   7,  10,  12,  15,  18,  21,  25,  29,  33,
     37,  42,  47,  52,  57,  62,  67,  73,  79,  85,  90,  97, 103, 109, 115, 121
  },
  {
    128, 125, 122, 119, 116, 113, 110, 107, 105, 102, 100,  97,  95,  92,  90,  88,
     86,  84,  82,  80,  78,  76,  74,  72,  70,  69,  67,  65,  64,  62,  60,  59,
     58,  56,  55,  53,  52,  51,  50,  48,  47,  46,  45,  44,  43,  42,  41,  40,
     39,  38,  37,  36,  35,  34,  33,  32,  32,  31,  30,  29,  29,  28,  27,  26,
     26,  25,  25,  24,  23,  23,  22,  22,  21,  21,  20,  20,  19,  19,  18,  18,
     17,  17,  16,  16,  16,  15,  15,  15,  14,  14,  13,  13,  13,  13,  12,  12,
     12,  11,  11,  11,  11,  10,  10,  10,  10,   9,   9,   9,   9,   8,   8,   8,
      8,   8,   7,   7,   7,   7,   7,   7,   6,   6,   6,   6,   6,   6,   5,   5
  },
};

namespace {

bool lfo_wav_is_centered(uint8_t wav_type) {
  constexpr uint16_t centered_mask = (1 << TRI_WAV) | (1 << SAW_WAV) |
                                     (1 << SQU_WAV) | (1 << RND_WAV) |
                                     (1 << SIN_WAV);
  return (centered_mask >> wav_type) & 1;
}

uint8_t lfo_legacy_shape_to_sps(uint8_t wav_type) {
  static const uint8_t map[] PROGMEM = {
      SIN_WAV, TRI_WAV, LIN_WAV, EXP_WAV, REV_LIN_WAV, REV_EXP_WAV,
      SQU_WAV, SAW_WAV, RND_WAV, STEP_WAV, LINLIN_WAV};
  if (wav_type > LFO_LEGACY_LINLIN_WAV) {
    return TRI_WAV;
  }
  return pgm_read_byte(&map[wav_type]);
}

bool lfo_legacy_shape_is_centered(uint8_t wav_type) {
  return wav_type == LFO_LEGACY_SIN_WAV || wav_type == LFO_LEGACY_TRI_WAV;
}

bool lfo_legacy_shape_uses_subtract(uint8_t wav_type) {
  return wav_type >= LFO_LEGACY_RAMP_WAV && wav_type <= LFO_LEGACY_EXP_WAV;
}

uint8_t lfo_sps_shape_to_legacy(uint8_t wav_type) {
  static const uint8_t map[] PROGMEM = {
      LFO_LEGACY_TRI_WAV,    LFO_LEGACY_SAW_WAV,  LFO_LEGACY_SQU_WAV,
      LFO_LEGACY_IRAMP_WAV,  LFO_LEGACY_EXP_WAV,  LFO_LEGACY_RND_WAV,
      LFO_LEGACY_RAMP_WAV,   LFO_LEGACY_IEXP_WAV, LFO_LEGACY_SIN_WAV,
      LFO_LEGACY_STEP_WAV,   LFO_LEGACY_LINLIN_WAV};
  if (wav_type > LINLIN_WAV) {
    return LFO_LEGACY_TRI_WAV;
  }
  return pgm_read_byte(&map[wav_type]);
}

uint8_t lfo_phase_index(uint16_t phase) {
  return (uint8_t)((phase & LFO_PHASE_MASK) >> 8);
}

uint8_t lfo_table_sample_phase(uint8_t table, uint16_t phase) {
  if (table >= LFO_TABLE_COUNT) {
    table = LFO_TABLE_SIN;
  }
  return pgm_read_byte(
      &LFOSeqTrack::wav_tables[table][lfo_phase_index(phase)]);
}

int16_t lfo_signed_tri(uint16_t phase) {
  uint16_t p = phase & LFO_PHASE_MASK;
  if (p < 0x2000U) {
    return p >> 6;
  }
  if (p < 0x6000U) {
    return 256 - (p >> 6);
  }
  return (p >> 6) - 512;
}

int16_t lfo_signed_saw(uint16_t phase) {
  return 128 - ((phase & LFO_PHASE_MASK) >> 7);
}

int16_t lfo_unipolar_decay(uint16_t phase) {
  return 128 - lfo_phase_index(phase);
}

int16_t lfo_unipolar_rise(uint16_t phase) {
  return lfo_phase_index(phase);
}

int16_t lfo_unipolar_linlin(uint16_t phase) {
  uint8_t idx = lfo_phase_index(phase);
  uint8_t raw = idx < 64 ? idx << 1 : (128 - idx) << 1;
  return raw;
}

int8_t lfo_seed_to_random_value(uint16_t seed) {
  return (int8_t)(((seed & 0x3FFFU) >> 7) - 64);
}

const int8_t lfo_preview_random_values[16] PROGMEM = {
    17, 53, 7, -4, -61, 0, 4, -59,
    10, 15, -39, 41, -61, 45, 48, 30};

int8_t lfo_preview_random(uint16_t phase) {
  uint8_t coarse = (phase & LFO_PHASE_MASK) >> 12;
  return (int8_t)pgm_read_byte(&lfo_preview_random_values[coarse]);
}

int16_t lfo_terminal_sample(uint8_t wav_type, uint16_t phase) {
  switch (wav_type) {
  case TRI_WAV:
  case SIN_WAV:
  case LIN_WAV:
  case EXP_WAV:
  case LINLIN_WAV:
    return 0;
  case REV_LIN_WAV:
  case REV_EXP_WAV:
  case STEP_WAV:
    return 128;
  case SAW_WAV:
  case SQU_WAV:
    return -128;
  default:
    return 0;
  }
}

int8_t lfo_next_random(uint16_t *state) {
  uint16_t next = state[0] + state[1];
  state[1] = state[0];
  state[0] = next;
  return lfo_seed_to_random_value(next);
}

uint8_t lfo_preview_to_u8(uint8_t wav_type, int16_t sample) {
  int16_t value = lfo_wav_is_centered(wav_type) ? ((sample + 128) >> 1)
                                                : sample;
  if (value < 0) {
    return 0;
  }
  if (value > 128) {
    return 128;
  }
  return (uint8_t)value;
}

uint16_t lfo_apply_speed_multiplier(uint16_t phase_inc, uint8_t multiplier) {
  if (multiplier > LFO_SPEED_MULT_1X) {
    uint8_t shift = multiplier - LFO_SPEED_MULT_1X;
    return phase_inc > (LFO_PHASE_MASK >> shift)
               ? LFO_PHASE_MASK
               : (uint16_t)(phase_inc << shift);
  }
  switch (multiplier) {
  case LFO_SPEED_MULT_1_2X:
    phase_inc >>= 1;
    break;
  case LFO_SPEED_MULT_1_4X:
    phase_inc >>= 2;
    break;
  case LFO_SPEED_MULT_1_10X:
    phase_inc /= 10;
    break;
  case LFO_SPEED_MULT_1_100X:
    phase_inc /= 100;
    break;
  default:
    break;
  }
  if (phase_inc == 0) {
    phase_inc = 1;
  }
  return phase_inc;
}

// MCL drives LFOs from the MIDI tick scheduler, so use the SPS curve shape at
// a fixed nominal tempo and let tick cadence provide musical tempo sync.
constexpr uint32_t kSpsNominalTempo = 120UL;
constexpr uint32_t kSpsTempoScale = 24UL;
constexpr uint32_t kSpsNominalTempoScaled =
    kSpsNominalTempo * kSpsTempoScale;

#if defined(__AVR__)
const uint16_t lfo_sps_phase_inc_hi_table[64] PROGMEM = {
      735,   782,   831,   883,   936,   993,  1051,  1113,
     1178,  1244,  1315,  1386,  1462,  1540,  1622,  1707,
     1795,  1887,  1982,  2081,  2181,  2288,  2397,  2511,
     2629,  2751,  2876,  3006,  3140,  3280,  3423,  3572,
     3723,  3881,  4044,  4211,  4385,  4562,  4746,  4935,
     5129,  5330,  5537,  5749,  5966,  6191,  6419,  6657,
     6899,  7149,  7405,  7669,  7940,  8216,  8501,  8795,
     9093,  9400,  9715, 10038, 10367, 10706, 11054, 11409
};
#endif

// Bits 0..5 store the new speed. Bits 6..7 select 1x, 1/2x, 1/4x, 1/10x.
// Generated from the legacy 96-step curve; worst phase increment error is 1.
const uint8_t lfo_legacy_speed_map[54] PROGMEM = {
  0x79, 0x79, 0x79, 0xB9, 0x53, 0x07, 0xF9, 0x93,
  0xE9, 0xE4, 0xE0, 0xDD, 0xDA, 0xD8, 0xD6, 0x02,
  0x02, 0x87, 0xD1, 0xD0, 0x43, 0x43, 0xCE, 0xCE,
  0x85, 0xCC, 0xCC, 0xCB, 0xCB, 0x01, 0x01, 0x01,
  0x01, 0x01, 0xC9, 0xC9, 0xC9, 0x83, 0x83, 0x83,
  0x83, 0x83, 0xC7, 0xC7, 0xC7, 0xC7, 0xC7, 0xC6,
  0xC6, 0xC6, 0xC6, 0xC6, 0xC6, 0xC6
};

uint8_t lfo_legacy_speed_packed(uint8_t legacy_speed) {
  legacy_speed &= 0x7FU;
  if (legacy_speed < 54) {
    return pgm_read_byte(&lfo_legacy_speed_map[legacy_speed]);
  }
  if (legacy_speed < 77) {
    return 0x41;
  }
  if (legacy_speed < 99) {
    return 0xC4;
  }
  return 0x81;
}

uint8_t lfo_legacy_speed_multiplier(uint8_t packed) {
  switch (packed >> 6) {
  case 1:
    return LFO_SPEED_MULT_1_2X;
  case 2:
    return LFO_SPEED_MULT_1_4X;
  case 3:
    return LFO_SPEED_MULT_1_10X;
  default:
    return LFO_SPEED_MULT_1X;
  }
}

} // namespace

void LegacyLFOSeqTrackData::init() {
  enable = false;
  wav_type = 0;
  speed = 0;
  mode = 0;
  legacy_offset_behaviour = LFO_OFFSET_CENTRE;
  pattern_mask = 0;
  length = 16;
  memset(legacy_runtime_padding, 0, sizeof(legacy_runtime_padding));
  for (uint8_t a = 0; a < NUM_LFO_PARAMS; a++) {
    params[a].init();
  }
}

void LegacyLFOSeqTrackData::load_data(const SeqLFOData &data) {
  wav_type = data.wav_type;
  speed = data.speed;
  mode = LFOSeqTrack::mode_base(data.mode);
  pattern_mask = data.pattern_mask;
  enable = data.enable;
  length = data.length;
  for (uint8_t i = 0; i < NUM_LFO_PARAMS; ++i) {
    params[i] = data.params[i];
  }
}

void LegacyLFOSeqTrackData::store_data(SeqLFOData *data) const {
  if (data == nullptr) {
    return;
  }
  data->wav_type = wav_type;
  data->speed = speed;
  data->mode = mode;
  data->pattern_mask = pattern_mask;
  data->enable = enable;
  data->length = length;
  for (uint8_t i = 0; i < NUM_LFO_PARAMS; ++i) {
    data->params[i] = params[i];
  }
}

void LFOSeqTrack::reset_shape_state() {
  state_phase = -1;
  random_value = 0;
}

void LFOSeqTrack::reset_phase() {
  phase = 0;
  reset_shape_state();
}

void LFOSeqTrack::reset_runtime() {
  phase = 0;
  phase_inc = speed_to_phase_increment(speed, speed_multiplier());
  step_count = 0;
  legacy_tick_counter = 0;
  uint16_t seed_base = ((uint16_t)static_cast<uint8_t>(device_idx) * 0x0101U) +
                       ((uint16_t)track_number * 0x0031U);
  random_state[0] = seed_base + 0x1234U;
  random_state[1] = seed_base + 0x5678U;
  reset_shape_state();
}

void LFOSeqTrack::load_data(const SeqLFOData &data) {
  wav_type = data.wav_type;
  if (wav_type >= LFO_SHAPE_COUNT) {
    wav_type = TRI_WAV;
  }
  speed = data.speed;
  mode = data.mode;
  pattern_mask = data.pattern_mask;
  enable = data.enable;
  length = data.length ? data.length : 16;
  for (uint8_t i = 0; i < NUM_LFO_PARAMS; ++i) {
    params[i] = data.params[i];
    last_wav_value[i] = 255;
  }
  reset_runtime();
}

void LFOSeqTrack::store_data(SeqLFOData *data) const {
  if (data == nullptr) {
    return;
  }
  data->wav_type = wav_type;
  data->speed = speed;
  data->mode = mode;
  data->pattern_mask = pattern_mask;
  data->enable = enable;
  data->length = length;
  for (uint8_t i = 0; i < NUM_LFO_PARAMS; ++i) {
    data->params[i] = params[i];
  }
}

void LFOSeqTrack::store_legacy_data(SeqLFOData *data) const {
  store_data(data);
  if (data != nullptr) {
    data->wav_type = lfo_sps_shape_to_legacy(wav_type);
  }
}

uint8_t LFOSeqTrack::get_wav_table_sample(uint8_t table, uint8_t n) {
  if (table >= LFO_TABLE_COUNT) {
    table = LFO_TABLE_SIN;
  }
  static_assert((WAV_LENGTH & (WAV_LENGTH - 1)) == 0,
                "WAV_LENGTH must remain a power of two");
  n &= WAV_LENGTH - 1;
  return pgm_read_byte(&wav_tables[table][n]);
}

int16_t LFOSeqTrack::get_preview_sample(uint8_t wav_type, uint16_t phase) {
  uint8_t wav = wav_type < LFO_SHAPE_COUNT ? wav_type : TRI_WAV;
  switch (wav) {
  case TRI_WAV:
    return lfo_signed_tri(phase);
  case SAW_WAV:
    return lfo_signed_saw(phase);
  case SQU_WAV:
    return (phase & 0x4000U) ? -128 : 128;
  case LIN_WAV:
    return lfo_unipolar_decay(phase);
  case EXP_WAV:
    return lfo_table_sample_phase(LFO_TABLE_EXP, phase);
  case RND_WAV:
    return lfo_preview_random(phase);
  case REV_LIN_WAV:
    return lfo_unipolar_rise(phase);
  case REV_EXP_WAV:
    return 128 - lfo_table_sample_phase(LFO_TABLE_EXP, phase);
  case SIN_WAV:
    return (int16_t)lfo_table_sample_phase(LFO_TABLE_SIN, phase) - 128;
  case STEP_WAV:
    return (phase & 0x4000U) ? 128 : 0;
  case LINLIN_WAV:
    return lfo_unipolar_linlin(phase);
  default:
    return 0;
  }
}

uint8_t LFOSeqTrack::get_preview_value(uint8_t wav_type, uint16_t phase) {
  uint8_t wav = wav_type < LFO_SHAPE_COUNT ? wav_type : TRI_WAV;
  return lfo_preview_to_u8(wav, get_preview_sample(wav, phase));
}

int16_t LFOSeqTrack::get_sample(uint8_t current_mode) {
  uint16_t render_phase = phase;
  if (mode_legacy_phase(mode) && (wav_type == SIN_WAV || wav_type == TRI_WAV)) {
    render_phase = (render_phase + 0x6000U) & LFO_PHASE_MASK;
  }

  if (wav_type == RND_WAV) {
    int8_t coarse = (render_phase & LFO_PHASE_MASK) >> 12;
    if (coarse != state_phase) {
      state_phase = coarse;
      random_value = lfo_next_random(random_state);
    }
    return random_value;
  }

  if (current_mode == LFO_MODE_ONE && phase == LFO_PHASE_MASK) {
    return lfo_terminal_sample(wav_type, render_phase);
  }

  return get_preview_sample(wav_type, render_phase);
}

uint16_t LFOSeqTrack::speed_to_phase_increment(uint8_t speed_) {
  return speed_to_phase_increment(speed_, LFO_SPEED_MULT_1X);
}

uint16_t LFOSeqTrack::speed_to_phase_increment(uint8_t speed_,
                                               uint8_t multiplier) {
#if defined(__AVR__)
  uint16_t phase_shift;
  if (speed_ < 64) {
    phase_shift = speed_ ? (uint16_t)speed_ * 12 : 1;
    if (speed_ >= 33) {
      --phase_shift;
    }
  } else {
    phase_shift = pgm_read_word(&lfo_sps_phase_inc_hi_table[speed_ - 64]);
  }
  return lfo_apply_speed_multiplier((uint16_t)phase_shift, multiplier);
#else
  uint32_t phase_shift;
  uint16_t speed14 =
      (uint16_t)(((uint32_t)speed_ * 0x3FFFUL + 63UL) / 127UL);
  if (speed14 < 0x2000U) {
    phase_shift =
        (kSpsNominalTempoScaled *
             ((uint32_t)speed14 * 0x10UL + 0x10UL) +
         0x3C8FEUL) /
        0x791FDUL;
  } else {
    uint32_t x =
        (uint32_t)speed14 * (((uint32_t)speed14 * speed14) >> 13);
    phase_shift =
        (kSpsNominalTempoScaled *
         (((uint32_t)speed14 * (x >> 17)) >> 10)) /
        0x4099UL;
  }
  if (phase_shift == 0) {
    phase_shift = 1;
  }
  if (phase_shift > LFO_PHASE_MASK) {
    phase_shift = LFO_PHASE_MASK;
  }
  return lfo_apply_speed_multiplier((uint16_t)phase_shift, multiplier);
#endif
}

void LFOSeqTrack::convert_legacy_data(const SeqLFOData &legacy_data,
                                      SeqLFOData *data) {
  if (data == nullptr) {
    return;
  }

  uint8_t legacy_wav_type = legacy_data.wav_type;
  uint8_t legacy_speed = legacy_data.speed;
  uint8_t legacy_mode = legacy_data.mode;

  *data = legacy_data;
  data->wav_type = lfo_legacy_shape_to_sps(legacy_wav_type);

  uint8_t base_mode = mode_base(legacy_mode);
  if (base_mode > LFO_MODE_ONE) {
    base_mode = LFO_MODE_FREE;
  }

  uint8_t packed = lfo_legacy_speed_packed(legacy_speed);
  data->speed = packed & 0x3F;
  data->mode = pack_mode(base_mode, lfo_legacy_speed_multiplier(packed));
  if (lfo_legacy_shape_is_centered(legacy_wav_type)) {
    data->mode |= LFO_MODE_LEGACY_PHASE;
    for (uint8_t i = 0; i < NUM_LFO_PARAMS; ++i) {
      data->params[i].depth >>= 1;
    }
  } else if (lfo_legacy_shape_uses_subtract(legacy_wav_type)) {
    data->mode |= LFO_MODE_LEGACY_SUBTRACT;
  }
  if (data->length == 0) {
    data->length = 16;
  }
}

void LFOSeqTrack::advance_phase(uint8_t current_mode) {
  uint16_t next = phase + phase_inc;
  if (current_mode == LFO_MODE_ONE && next >= LFO_PHASE_LENGTH) {
    phase = LFO_PHASE_MASK;
    return;
  }
  phase = next & LFO_PHASE_MASK;
}

void LFOSeqTrack::set_wav_type(uint8_t _wav_type) {
  uint8_t wav = _wav_type < LFO_SHAPE_COUNT ? _wav_type : TRI_WAV;
  if (wav_type != wav) {
    wav_type = wav;
    mode &= ~LFO_MODE_LEGACY_FLAGS;
    reset_shape_state();
    for (uint8_t i = 0; i < NUM_LFO_PARAMS; ++i) {
      last_wav_value[i] = 255;
    }
  }
}

void LFOSeqTrack::set_speed(uint8_t _speed) {
  speed = _speed;
  phase_inc = speed_to_phase_increment(speed, speed_multiplier());
}

void LFOSeqTrack::set_speed_multiplier(uint8_t multiplier) {
  mode = (mode & LFO_MODE_LEGACY_FLAGS) | pack_mode(base_mode(), multiplier);
  phase_inc = speed_to_phase_increment(speed, speed_multiplier());
}

uint8_t LFOSeqTrack::get_wav_value(uint8_t offset, uint8_t param_id,
                                   int16_t lfo_sample) {
  int16_t depth = params[param_id].depth;
  int16_t delta = (lfo_sample * depth) / 128;
  bool offset_max = mode_legacy_subtract(mode) || !lfo_wav_is_centered(wav_type);
  int16_t sample = offset_max ? offset - delta : offset + delta;

  if (sample > 127) {
    return 127;
  }
  if (sample < 0) {
    return 0;
  }

  return (uint8_t)sample;
}

void LFOSeqTrack::seq(MidiUartClass *uart_, MidiUartClass *uart2_) {
  uint8_t current_mode = base_mode();
  if (current_mode == LFO_MODE_TRACK_TRIG &&
      mcl_seq.lfo_track_trig_fired(device_idx, track_number)) {
    reset_phase();
  } else if ((legacy_tick_counter == 0) &&
             (current_mode != LFO_MODE_FREE) &&
             current_mode != LFO_MODE_TRACK_TRIG &&
             IS_BIT_SET64(pattern_mask, step_count)) {
    reset_phase();
  }

  if (enable) {
    int16_t lfo_sample = get_sample(current_mode);
    for (uint8_t i = 0; i < NUM_LFO_PARAMS; i++) {
      if (params[i].dest == 0) {
        continue;
      }
      uint8_t dest = params[i].dest;
      uint8_t param = params[i].param;
      uint8_t offset = params[i].offset;
      uint8_t wav_value = get_wav_value(offset, i, lfo_sample);
      if (last_wav_value[i] != wav_value) {
        LFOTrackRef::send_modulated_param(device_idx, dest, param, wav_value,
                                          uart_, uart2_, offset);

        last_wav_value[i] = wav_value;
      }
    }
  }

  advance_phase(current_mode);

  if (legacy_tick_counter >= 11) {
    legacy_tick_counter = 0;
    uint8_t seq_length = length ? length : 16;
    if (step_count >= seq_length - 1) {
      step_count = 0;
    } else {
      step_count++;
    }
  } else {
    legacy_tick_counter++;
  }
}

void LFOSeqTrack::reset_params() {
//  while (MidiClock.state == 2 && mod12_counter == MidiClock.mod12_counter) {};

  for (uint8_t i = 0; i < NUM_LFO_PARAMS; i++) {
    if (params[i].dest == 0) {
      continue;
    }
    uint8_t dest = params[i].dest;
    uint8_t param = params[i].param;
    uint8_t wav_value = params[i].offset;
    LFOTrackRef::send_modulated_param(device_idx, dest, param, wav_value,
                                      mcl_seq.primary_output,
                                      mcl_seq.secondary_output, wav_value);
    last_wav_value[i] = 255;
  }
}
