
/*******************************************************************************
* generated by lcd-image-converter rev.129188f from 2019-07-09 00:20:51 +0500
* image
* filename: C:/Users/Yatao/Documents/Arduino/hardware/MIDICtrl20_MegaCommand/art/sprites/route_icon_3.xml
* name: Image
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_Image[75] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙███∙∙∙∙███∙∙∙∙███∙∙∙∙
    // ∙∙∙███∙∙∙∙███∙∙∙∙███∙∙∙∙
    // ∙∙█████∙∙█████∙∙█████∙∙∙
    // ████████████████████████
    // ████████████████████████
    // ∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙███∙█████████∙∙∙█████∙
    // ∙∙█∙∙∙█∙∙∙█∙∙∙█∙∙∙█∙∙∙█∙
    // ∙∙█∙∙∙█∙∙∙█∙∙∙█∙∙∙█∙∙∙█∙
    // ∙███∙███∙███∙███∙███∙███
    // ∙█∙█∙█∙█∙█∙█∙█∙█∙█∙█∙█∙█
    // ∙███∙███∙███∙███∙███∙███
    // ∙∙█∙∙∙∙∙∙∙█∙∙∙∙∙∙∙█∙∙∙∙∙
    // ∙███∙███∙███∙███∙███∙███
    // ∙█∙█∙█∙███∙█∙█∙███∙███∙█
    // ∙███∙███∙███∙███∙███∙███
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙███∙█∙█∙███∙███∙∙
    // ∙∙∙█∙█∙█∙█∙█∙█∙∙█∙∙█∙∙∙∙
    // ∙∙∙█∙█∙█∙█∙█∙█∙∙█∙∙███∙∙
    // ∙∙∙██∙∙█∙█∙█∙█∙∙█∙∙█∙∙∙∙
    // ∙∙∙█∙█∙███∙███∙∙█∙∙███∙∙
    0x00, 0x00, 0x00, 
    0x00, 0x00, 0x00, 
    0x1c, 0x38, 0x70, 
    0x1c, 0x38, 0x70, 
    0x3e, 0x7c, 0xf8, 
    0xff, 0xff, 0xff, 
    0xff, 0xff, 0xff, 
    0x08, 0x10, 0x20, 
    0x08, 0x10, 0x20, 
    0x3b, 0xfe, 0x3e, 
    0x22, 0x22, 0x22, 
    0x22, 0x22, 0x22, 
    0x77, 0x77, 0x77, 
    0x55, 0x55, 0x55, 
    0x77, 0x77, 0x77, 
    0x20, 0x20, 0x20, 
    0x77, 0x77, 0x77, 
    0x55, 0xd5, 0xdd, 
    0x77, 0x77, 0x77, 
    0x00, 0x00, 0x00, 
    0x19, 0xd5, 0xdc, 
    0x15, 0x54, 0x90, 
    0x15, 0x54, 0x9c, 
    0x19, 0x54, 0x90, 
    0x15, 0xdc, 0x9c
};
const tImage Image = { image_data_Image, 24, 25,
    8 };

