#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

namespace {

struct Export {
    std::string semantic;
    std::string symbol;
    bool required = false;
    std::string declaration;
};

std::string readFile(const char* path) {
    std::ifstream input(path, std::ios::binary);
    std::ostringstream output;
    output << input.rdbuf();
    return output.str();
}

bool writeFile(const char* path, const std::string& contents) {
    std::ofstream output(path, std::ios::binary | std::ios::trunc);
    output << contents;
    return output.good();
}

}  // namespace

int main(int argc, char** argv) {
    if (argc != 6) {
        std::cerr << "usage: wasm_abi_codegen <abi.def> <module.template.json> "
                     "<module.json> <exports.h> <linker.rsp>\n";
        return 2;
    }

    const std::regex entry(
        R"ABI(^\s*MCL_WASM_EXPORT\("([^"]+)",\s*"([^"]+)",\s*(required|optional),\s*"([^"]+)"\)\s*$)ABI");
    std::istringstream lines(readFile(argv[1]));
    std::vector<Export> exports;
    std::string line;
    int lineNumber = 0;
    while (std::getline(lines, line)) {
        ++lineNumber;
        if (line.empty() || line.find_first_not_of(" \t") == std::string::npos ||
            line.find("//") == line.find_first_not_of(" \t"))
            continue;
        std::smatch match;
        if (!std::regex_match(line, match, entry)) {
            std::cerr << argv[1] << ':' << lineNumber
                      << ": invalid ABI entry\n";
            return 1;
        }
        exports.push_back(
            {match[1].str(), match[2].str(), match[3] == "required",
             match[4].str()});
    }
    if (exports.empty()) {
        std::cerr << argv[1] << ": no ABI exports\n";
        return 1;
    }

    std::ostringstream json;
    json << "{\n";
    for (std::size_t i = 0; i < exports.size(); ++i) {
        json << "    \"" << exports[i].semantic << "\": \""
             << exports[i].symbol << "\""
             << (i + 1 == exports.size() ? "\n" : ",\n");
    }
    json << "  }";

    std::string manifest = readFile(argv[2]);
    constexpr const char* marker = "@MCL_WASM_EXPORTS@";
    const auto markerPosition = manifest.find(marker);
    if (markerPosition == std::string::npos) {
        std::cerr << argv[2] << ": missing " << marker << '\n';
        return 1;
    }
    manifest.replace(markerPosition, std::char_traits<char>::length(marker),
                     json.str());

    std::ostringstream header;
    header << "// Generated by tools/wasm_abi_codegen.cpp from " << argv[1]
           << ". Do not edit.\n#pragma once\n\n#include <stdint.h>\n\n"
              "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";
    for (const auto& item : exports)
        header << item.declaration << '\n';
    header << "\n#ifdef __cplusplus\n}\n#endif\n";

    std::ostringstream linker;
    linker << "-Wl,--export=__wasm_call_ctors\n";
    for (const auto& item : exports)
        linker << "-Wl,--export=" << item.symbol << '\n';

    if (!writeFile(argv[3], manifest) || !writeFile(argv[4], header.str()) ||
        !writeFile(argv[5], linker.str())) {
        std::cerr << "failed to write generated ABI outputs\n";
        return 1;
    }
    return 0;
}
